name: Build Desktop Apps

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master
    paths-ignore:
      - 'README.md'

jobs:
  build-mac-tauri:
    name: "Build Mac (.dmg)"
    runs-on: macos-latest
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v4

      - name: "Setup Node.js"
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: "Setup Rust (Apple Silicon & Intel)"
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: "aarch64-apple-darwin, x86_64-apple-darwin"

      - name: "Install npm dependencies"
        run: npm install --no-audit --no-fund

      - name: "Build Tauri Mac App"
        run: npx tauri build --target universal-apple-darwin --ci

      - name: "Upload Mac DMG Artifact"
        uses: actions/upload-artifact@v4
        with:
          name: FAE-Dashboard-Mac-Universal-DMG
          path: src-tauri/target/**/bundle/dmg/*.dmg
          if-no-files-found: error

  build-win-tauri:
    name: "Build Windows (.exe)"
    runs-on: windows-latest
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v4

      - name: "Setup Node.js"
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: "Setup Rust"
        uses: dtolnay/rust-toolchain@stable

      - name: "Install npm dependencies"
        run: npm install --no-audit --no-fund

      - name: "Build Tauri Windows App"
        run: npx tauri build --ci

      - name: "Upload Windows EXE Artifact"
        uses: actions/upload-artifact@v4
        with:
          name: FAE-Dashboard-Windows-EXE
          path: src-tauri/target/**/bundle/nsis/*.exe
          if-no-files-found: error
